# AIPS Configuration File
# Customize parameters for stock validation

# Price Range Settings
price_range:
  min: 1.0
  max: 100.0
  currency: "INR"

# Market Settings
market:
  exchange: "NSE"  # NSE or BSE
  country: "IN"
  market_suffix: ".NS"  # .NS for NSE, .BO for BSE

# Analysis Periods
analysis_periods:
  short_term_days: 30
  medium_term_days: 90
  long_term_days: 365
  historical_years: 5

# Technical Indicators
technical_indicators:
  moving_averages: [20, 50, 200]
  rsi_period: 14
  rsi_overbought: 70
  rsi_oversold: 30
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  bollinger_period: 20
  bollinger_std: 2
  volume_sma_period: 20

# Fundamental Thresholds
fundamental_thresholds:
  min_market_cap: 50000000  # 5 Crores
  max_debt_equity: 2.0
  min_current_ratio: 1.0
  min_roe: 10.0  # percentage
  min_profit_margin: 5.0  # percentage
  min_revenue_growth: 10.0  # percentage year-over-year

# Scoring Weights (must sum to 100)
scoring_weights:
  company_profile: 15
  fundamental_analysis: 40
  technical_analysis: 30
  risk_factors: 15

# Risk Flags
risk_flags:
  check_litigation: true
  check_regulatory_issues: true
  check_promoter_pledge: true
  max_acceptable_pledge: 50.0  # percentage
  min_trading_volume: 10000  # shares per day
  min_promoter_holding: 30.0  # percentage

# Output Settings
output:
  format: ["html", "excel", "json"]
  save_charts: true
  chart_format: "png"
  report_directory: "reports"
  log_level: "INFO"

# Data Sources
data_sources:
  primary: "yfinance"
  fallback: ["screener.in", "moneycontrol"]
  cache_duration_hours: 24
