services:
  - type: web
    name: backend
    env: docker
    rootDir: Backend
    plan: free
    region: frankfurt
    autoDeploy: true
    healthCheckPath: /expenses/balance
    dockerCommand: ""
    envVars:
      - key: FLASK_ENV
        value: production

  - type: static_site
    name: frontend
    rootDir: my-chalkboard-cash
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: backend
          property: url
      - key: VITE_SAMPLE_MODE
        value: "false"
